<?php
$answer=
$_POST['jawabansiswa1'].
$_POST['jawabansiswa2'].
$_POST['jawabansiswa3'].
$_POST['jawabansiswa4'].
$_POST['jawabansiswa5'].
$_POST['jawabansiswa6'].
$_POST['jawabansiswa7'].
$_POST['jawabansiswa8'].
$_POST['jawabansiswa9'].
$_POST['jawabansiswa10'].
$_POST['jawabansiswa11'].
$_POST['jawabansiswa12'].
$_POST['jawabansiswa13'].
$_POST['jawabansiswa14'].
$_POST['jawabansiswa15'].
$_POST['jawabansiswa16'].
$_POST['jawabansiswa17'].
$_POST['jawabansiswa18'].
$_POST['jawabansiswa19'].
$_POST['jawabansiswa20'].
$_POST['jawabansiswa21'].
$_POST['jawabansiswa22'].
$_POST['jawabansiswa23'].
$_POST['jawabansiswa24'].
$_POST['jawabansiswa25'].
$_POST['jawabansiswa26'].
$_POST['jawabansiswa27'].
$_POST['jawabansiswa28'].
$_POST['jawabansiswa29'].
$_POST['jawabansiswa30'].
$_POST['jawabansiswa31'].
$_POST['jawabansiswa32'].
$_POST['jawabansiswa33'].
$_POST['jawabansiswa34'].
$_POST['jawabansiswa35'].
$_POST['jawabansiswa36'].
$_POST['jawabansiswa37'].
$_POST['jawabansiswa38'].
$_POST['jawabansiswa39'].
$_POST['jawabansiswa40'].
$_POST['jawabansiswa41'].
$_POST['jawabansiswa42'].
$_POST['jawabansiswa43'].
$_POST['jawabansiswa44'].
$_POST['jawabansiswa45'].
$_POST['jawabansiswa46'].
$_POST['jawabansiswa47'].
$_POST['jawabansiswa48'].
$_POST['jawabansiswa49'].
$_POST['jawabansiswa50'].
$_POST['jawabansiswa51'].
$_POST['jawabansiswa52'].
$_POST['jawabansiswa53'].
$_POST['jawabansiswa54'].
$_POST['jawabansiswa55'].
$_POST['jawabansiswa56'].
$_POST['jawabansiswa57'].
$_POST['jawabansiswa58'].
$_POST['jawabansiswa59'].
$_POST['jawabansiswa60'].
$_POST['jawabansiswa61'].
$_POST['jawabansiswa62'].
$_POST['jawabansiswa63'].
$_POST['jawabansiswa64'].
$_POST['jawabansiswa65'].
$_POST['jawabansiswa66'].
$_POST['jawabansiswa67'].
$_POST['jawabansiswa68'].
$_POST['jawabansiswa69'].
$_POST['jawabansiswa70'].
$_POST['jawabansiswa71'].
$_POST['jawabansiswa72'].
$_POST['jawabansiswa73'].
$_POST['jawabansiswa74'].
$_POST['jawabansiswa75'].
$_POST['jawabansiswa76'].
$_POST['jawabansiswa77'].
$_POST['jawabansiswa78'].
$_POST['jawabansiswa79'].
$_POST['jawabansiswa80'].
$_POST['jawabansiswa81'].
$_POST['jawabansiswa82'].
$_POST['jawabansiswa83'].
$_POST['jawabansiswa84'].
$_POST['jawabansiswa85'].
$_POST['jawabansiswa86'].
$_POST['jawabansiswa87'].
$_POST['jawabansiswa88'].
$_POST['jawabansiswa89'].
$_POST['jawabansiswa90'].
$_POST['jawabansiswa91'].
$_POST['jawabansiswa92'].
$_POST['jawabansiswa93'].
$_POST['jawabansiswa94'].
$_POST['jawabansiswa95'].
$_POST['jawabansiswa96'].
$_POST['jawabansiswa97'].
$_POST['jawabansiswa98'].
$_POST['jawabansiswa99'].
$_POST['jawabansiswa100'];
?>